### ISSUE TITLE
Problem with unicode character

### ISSUE THREAD

**Issue by Niklas123Niklas** [icarecti/chatgpt_macro_for_texstudio#5]
Hi there,

thanks for providing this nice macro for TeXstudio. I use it in combination with LuaLaTeX, where unicode character are allowed. This sometimes lead to chatgpt answers with unicode characters, that cannot be printed. The error message looks like this:
`Traceback (most recent call last): File "D:\Programme\TeXstudio Settings\openai_python_script.py", line 39, in <module> print(content, end='', flush=True) File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode character '\u0394' in position 0: character maps to `<undefined>``

Is there anything you can do about? Unfortunately, I did not figure a way out to resolve this. 
Cheers
Niklas

**Comment by icarecti** [comment]
Hi Niklas,
thank you for submitting your issue. I dont have the resources to replicate your bug right now. Does the AI generated solution to your issue in the comment above work? If not let me know and I can look further into that issue.
Greetings Steve
